/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppointmentRequest {
  'whatsappConfirmation' : boolean,
  'serviceType' : string,
  'name' : string,
  'createdAt' : Time,
  'preferredDate' : string,
  'preferredTime' : string,
  'phone' : string,
}
export interface ContactLead {
  'name' : string,
  'createdAt' : Time,
  'message' : string,
  'phone' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'createAppointment' : ActorMethod<[string, AppointmentRequest], undefined>,
  'createContactLead' : ActorMethod<[string, ContactLead], undefined>,
  'getAllAppointmentsByTime' : ActorMethod<[], Array<AppointmentRequest>>,
  'getAllContactsByTime' : ActorMethod<[], Array<ContactLead>>,
  'getAppointmentsByDate' : ActorMethod<[string], Array<AppointmentRequest>>,
  'getAppointmentsByName' : ActorMethod<[string], Array<AppointmentRequest>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];