/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const AppointmentRequest = IDL.Record({
  'whatsappConfirmation' : IDL.Bool,
  'serviceType' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'preferredDate' : IDL.Text,
  'preferredTime' : IDL.Text,
  'phone' : IDL.Text,
});
export const ContactLead = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'createAppointment' : IDL.Func([IDL.Text, AppointmentRequest], [], []),
  'createContactLead' : IDL.Func([IDL.Text, ContactLead], [], []),
  'getAllAppointmentsByTime' : IDL.Func(
      [],
      [IDL.Vec(AppointmentRequest)],
      ['query'],
    ),
  'getAllContactsByTime' : IDL.Func([], [IDL.Vec(ContactLead)], ['query']),
  'getAppointmentsByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AppointmentRequest)],
      ['query'],
    ),
  'getAppointmentsByName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AppointmentRequest)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const AppointmentRequest = IDL.Record({
    'whatsappConfirmation' : IDL.Bool,
    'serviceType' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'preferredDate' : IDL.Text,
    'preferredTime' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ContactLead = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Time,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'createAppointment' : IDL.Func([IDL.Text, AppointmentRequest], [], []),
    'createContactLead' : IDL.Func([IDL.Text, ContactLead], [], []),
    'getAllAppointmentsByTime' : IDL.Func(
        [],
        [IDL.Vec(AppointmentRequest)],
        ['query'],
      ),
    'getAllContactsByTime' : IDL.Func([], [IDL.Vec(ContactLead)], ['query']),
    'getAppointmentsByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AppointmentRequest)],
        ['query'],
      ),
    'getAppointmentsByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AppointmentRequest)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };